train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: datasets/div2k/DIV2K_train_HR
      repeat: 20
      cache: in_memory
  wrapper:
    name: ope-sample-train-2
    args:
      inp_size: 48
      scale_min: 4
      scale_max: 4
      augment: true
      norm: true
      sample_q: 2304
  batch_size: 16
val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./datasets/div2k/DIV2K_valid_HR
      first_k: 10
      repeat: 10
      cache: in_memory
  wrapper:
    name: ope-patch-eval
    args:
      inp_size: 48
      scale_factor: 4
      augment: true
      norm: true
  batch_size: 16
model:
  name: OPE-net
  args:
    max_freq: 3
    srnet_spec:
      name: rdn
      args:
        n_feats: 147
        RDNconfig: B
        RDNkSize: 3
optimizer:
  name: adam
  args:
    lr: 0.0001
epoch_max: 1000
multi_step_lr:
  milestones:
  - 200
  - 400
  - 600
  - 800
  gamma: 0.5
epoch_val: 1
epoch_save: 20
